package com.medenrollment.test.sql;

public class EnrollmentSystemSQLS {
	
	public static String getAllEnrollees = "SELECT A.ENROLEE_ID,A.ENROLLEE_NAME,A.ENROLLEE_STATUS,A.ENROLLEE_DOB,A.ENROLLEE_PHONENO,B.DEPENDENT_ID,B.DEPENDENT_NAME,B.DEPENDENT_DOB,B.DEPENDENT_RELATIONSHIP FROM"+
											"ENROLEE A JOIN DEPENDENT B WHERE A.ENROLLEE_ID = B.ENROLLEE_ID"; 
	
	public static String addEnrollee = "INSERT INTO ENROLLEE (ENROLLEE_ID,ENROLEE_NAME,ENROLLEE_STATUS,ENROLEE_DOB,ENROLEE_PHONENO) VALUES(?,?,?,?,?)";
	public static String updateEnrollee="UPDATE ENROLLEE SET ENROLLEE_NAME=?,ENROLLEE_STATUS=?,ENROLLEE_DOB=?,ENROLLEE_PHONENO=? WHERE ENROLEE_ID=?";
	public static String deleteEnrollee = "DELETE FROM ENROLLEE WHERE ENROLEE_ID=?";
	
	public static String getAllDependents = "SELECT DEPENDENT_ID,DEPENDENT_NAME,DEPENDENT_DOB,DEPENDENT_RELATIONSHIP WHERE ENROLEE_ID=?";
	public static String addDependent = "INSERT INTO DEPENDENT (DEPENDENT_ID,DEPENDENT_NAME,DEPENDENT_DOB,DEPENDENT_RELATIONSHIP) VALUES(?,?,?,?)";
	public static String updateDependent = "UPDATE DEPENDENT SET DEPENDENT_NAME=?,DEPENDENT_DOB=?,DEPENDENT_RELATIONSHIP=? WHERE ENROLLEE_ID =? AND DEPENDENT_ID=?";
	public static String deleteDependent = "DELETE FROM DEPENDENT WHERE ENROLEE_ID=? AND DEPENDENT_ID=?";

}
